create user ocw identified by CloudWorld$2023;
grant create job to ocw;
grant create trigger to ocw;
grant create materialized view to ocw;
grant create dimension to ocw;
grant create operator to ocw;
grant create indextype to ocw;
grant create view to ocw;
grant create session to ocw;
grant create table to ocw;
grant create type to ocw;
grant create synonym to ocw;
grant create sequence to ocw;
grant create cluster to ocw;
grant create procedure to ocw;
grant unlimited tablespace to ocw;
